spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    username: root
    password: mysql
    dbcp2:
      driver: com.mysql.jdbc.Driver
  session:
    store-type: none
security:
  basic:
    enabled: false
#  browser:
#    loginPage: /demo-page.html